name: CI-CD

on: 
  push: 
    branches: ["master"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain source code
        uses: actions/checkout@v4  
      - name: Autenticate on Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: echo "Build docker image"
      - name: Send image
        run: echo "Sending docker image"

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticate on Aws
        run: echo "AWS configure"
      - name: Configure kubectl
        run: echo "Kubectl configure"
      - name: Apply manifest
        run: echo "Kubectl apply"
